EasyNotes.WebApp.Mvc/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EasyNotes.WebApp.Mvc.Data;
using EasyNotes.WebApp.Mvc.Models;
using Microsoft.AspNetCore.Authorization;
using EasyNotes.WebApp.Mvc.Helpers;

namespace EasyNotes.WebApp.Mvc.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CategoriesController(ApplicationDbContext context)
        {
            _db = context;
        }

        [Authorize(Roles = Roles.Executive)]
        public IActionResult Index()
        {
            var categoryList = new List<Category>();
            var userName = User.Identity.Name;
            //IEnumerable<Note> objNotesList = _context.Notes.ToList();
            foreach (Category category in _db.Categories)
            {
                if (category.UserName == userName)
                {
                    categoryList.Add(category);
                }
            }
            return View(categoryList);
        }
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        // PoST: Notes/ShowSearchResults

        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            return View("Index", await _db.Categories.Where(j => j.CategoryName.Contains(SearchPhrase)).ToListAsync());
        }
        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {

            if (ModelState.IsValid)
            {
                obj.Id = Guid.NewGuid();
                obj.Notes = new List<Note>();
                obj.UserName = User.Identity.Name;
                _db.Categories.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Category successfully created!";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(Guid id)
        {
            if (id == null || id == Guid.Empty)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Categories.Find(id);
            /*var noteFromDbFirst = _context.Notes.FirstOrDefault(x => x.Id == id);
            var noteFromDbSingle = _context.Notes.SingleOrDefault(x => x.Id == id);*/

            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
            
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            
            if (ModelState.IsValid)
            {
                obj.UserName = User.Identity.Name.ToLower();
                _db.Categories.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Category successfully updated!";
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        //GET
        public IActionResult Delete(Guid id)
        {
            if (id == null || id == Guid.Empty)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Categories.Find(id);
            /*var noteFromDbFirst = _context.Notes.FirstOrDefault(x => x.Id == id);
            var noteFromDbSingle = _context.Notes.SingleOrDefault(x => x.Id == id);*/

            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }

        //POST
        [HttpPost, ActionName("DeletePOST")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(Guid id)
        {
            var obj = _db.Categories.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Categories.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Category successfully deleted!";
            return RedirectToAction("Index");
        }
    }
}

EasyNotes.WebApp.Mvc/Controllers/NoteViewController.cs
using EasyNotes.WebApp.Mvc.Data;
using EasyNotes.WebApp.Mvc.Helpers;
using EasyNotes.WebApp.Mvc.Models;
using EasyNotes.WebApp.Mvc.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting.Internal;

namespace EasyNotes.WebApp.Mvc.Controllers
{
    public class NoteViewController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly HostingEnvironment? _hostingEnvironment;
        [BindProperty]
        public NoteViewModel NoteVM { get; set; }

        public NoteViewController(ApplicationDbContext db)
        {
            _db = db;
           // _hostingEnvironment = hostingEnvironment;
            NoteVM = new NoteViewModel()
            {
                Categories = _db.Categories.ToList(),
                VNote = new Note()
            };
        }
        [Authorize(Roles = Roles.Executive)]
        public IActionResult Index()
        {
            var categoryList = new List<Note>();
            var userName = User.Identity.Name;
            //IEnumerable<Note> objNotesList = _context.Notes.ToList();
            foreach (Note note in _db.Notes)
            {
                if (note.UserName == userName)
                {
                    categoryList.Add(note);
                }
            }
            return View(categoryList);
            /*var notesList = new List<Note>();
            var model = _db.Notes.Include(m => m.Category);
            return View(model) ;*/
        }

        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        // PoST: Notes/ShowSearchResults

        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            return View("Index", await _db.Notes.Where(j => j.Name.Contains(SearchPhrase)).ToListAsync());
        }
        //HTTPGET
        public IActionResult Create()
        {
            return View(NoteVM);
        }

        [HttpPost,ActionName("Create")]
        [ValidateAntiForgeryToken]
        public IActionResult CreatePost()
        {
            NoteVM.VNote.UserName = User.Identity.Name;
            if (!ModelState.IsValid)
            {
                
                return View(NoteVM);
            }
            _db.Notes.Add(NoteVM.VNote);
            _db.SaveChanges();

           /* var NoteID = NoteVM.VNote.Id;

            string wwrootPath = _hostingEnvironment.ContentRootPath;
            var files = HttpContext.Request.Form.Files;
            var SavedNote = _db.Notes.Find(NoteID);
            if (files.Count != 0)
            {
                var imagePath = @"images\note\";
                var Extention = Path.GetExtension(files[0].FileName);
                var RelativeImagePat = imagePath + NoteID + Extention;
                var AbsImagePath = Path.Combine(wwrootPath, RelativeImagePat);

                using (var fileStream = new FileStream(AbsImagePath, FileMode.Create))
                {
                    files[0].CopyTo(fileStream);
                    _db.SaveChanges();
                }
            }*/


            TempData["success"] = "Note successfully created!";
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(Guid id)
        {
            NoteVM.VNote = _db.Notes.Include(m => m.Category).SingleOrDefault(m => m.Id == id);
            if(NoteVM.VNote == null)
            {
                return NotFound();
            }
            return View(NoteVM);
        }
        [HttpPost,ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public IActionResult EditPost()
        {
            if(!ModelState.IsValid)
            {
                return View(NoteVM);
            }

            _db.Update(NoteVM.VNote);
            _db.SaveChanges();
            TempData["success"] = "Note successfully updated!";
            return RedirectToAction(nameof(Index));
        }

        
        public IActionResult Delete (Guid id)
        {
            Note note = _db.Notes.Find(id);
            if(note == null)
            {
                return NotFound();
            }
            _db.Notes.Remove(note);
            _db.SaveChanges();
            TempData["success"] = "Note successfully deleted!";
            return RedirectToAction(nameof(Index));
        }
    }
}

EasyNotes.WebApp.Mvc/Controllers/PublicNotesController.cs
using EasyNotes.WebApp.Mvc.Data;
using EasyNotes.WebApp.Mvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace EasyNotes.WebApp.Mvc.Controllers
{
    public class PublicNotesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public PublicNotesController(ApplicationDbContext context)
        {
            _db = context;
        }
        public IActionResult Index()
        {
            IEnumerable<PublicNote> objNotesList = _db.PublicNotes.ToList();
            return View(objNotesList);
        }
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        // PoST: Notes/ShowSearchResults

        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            return View("Index",  _db.PublicNotes.Where(j => j.Id.Equals(SearchPhrase)).ToList());
        }
        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PublicNote obj)
        {

            if (ModelState.IsValid)
            {
                obj.Id = Guid.NewGuid();
                obj.CreateDate = DateTime.Now;
                _db.PublicNotes.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Note successfully created!";
                return RedirectToAction("Index");
            }

            return View(obj);
        }
    }
}

EasyNotes.WebApp.Mvc/Views/Shared/_Layout.cshtml
@using EasyNotes.WebApp.Mvc.Helpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Easy Notes</title>
    <link rel="stylesheet" href="~/css/BootsWatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EasyNotes.WebApp.Mvc.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Easy Notes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                        <li class="nav-item">
                            <a  class="nav-link text-white" asp-area="" asp-controller="NoteView" asp-action="Index">Notes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        }
                         <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="PublicNotes" asp-action="Index">Public</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Contacts</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="https://www.codewars.com/users/blackoutcoder">Follow me on CodeWars</a>
                                    <a class="dropdown-item" href="https://www.linkedin.com/in/roman-repic-174b44173/">Follow me on LinkedIn</a>
                                    <a class="dropdown-item" href="https://github.com/blackoutcoder">Visit me on GitHub</a>
                                    @if(User.IsInRole(Roles.Admin))
                                    {
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-controller="NoteView" asp-action="Index">For Admins</a>
                                    }
                                </div>
                        </li>  
                        <li class="nav-item">
                           
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-gradient bg-black-50  box-shadow text-black-50">
        <div class="container">
            &copy; 2022 - Easy Notes by Roman Repic (aka RBoC_x84) - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EasyNotes.WebApp.Mvc/Views/Shared/_Notifications.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">toastr.success('@TempData["success"]');</script>
}

@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">toastr.success('@TempData["error"]');</script>
}